# thanks Platane for this great idea. Source: https://github.com/Platane/snk
name: generate svgs for the README

on:
  # run automatically every 24 hours
  schedule:
    - cron: "0 */24 * * *" 
  # allows to manually run the job at any time
  workflow_dispatch:
  # run on every push on the master branch
  push:
    branches:
    - master
jobs:
  snake:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      # generates a snake game from a github user (<github_user_name>) contributions graph, output a svg animation at <svg_out_path>
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=#306998&color_dots=#FFFFBF,#FFE873,#FFD43B,#f1c000,#e68801
            dist/github-contribution-grid-snake-dark.svg?color_snake=#306998&color_dots=#161B22,#FFE873,#FFD43B,#f1c000,#e68801
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # push the content of <build_dir> to a branch
      # the content will be available at https://raw.githubusercontent.com/<github_user>/<repository>/<target_branch>/<file> , or as github page
      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  trophy:
    runs-on: ubuntu-lates
    timeout-minutes: 10
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6

      - name: Generate trophy card
        uses: soulteary/github-profile-trophy-action@v1.0.0
        with:
          options: 'username=${{ github.repository_owner }}row=1&theme=radical'
          path: dist/trophy.svg
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: push trophy.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6

      - name: Generate stats card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: username=${{ github.repository_owner }}&theme=radical&show_icons=true&custom_title=My%20Github%20Stats&count_private=true
          path: dist/stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate top languages card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          options: username=${{ github.repository_owner }}&theme=radical&layout=compact&langs_count=10
          path: dist/top-langs.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate pin card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=luigiMinardi&repo=reaction-test
          path: dist/pin-luigiMinardi-reaction-test.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: push *.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
